# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flooding.py
# Anna Bebbington
# Created on: 2020-10-16 11:31:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Script to Clip floodzones to basin shapefile, and Select from the clipped shapefile areas in a 'special flood hazard area'
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
floodzones = "floodzones"
basin = "basin"
flood_Clip_shp = "C:\\Programming for GIS\\Lab_1_Geoprocessing_ArcGIS\\Results\\flood_Clip.shp"
flooding_shp = "C:\\Programming for GIS\\Lab_1_Geoprocessing_ArcGIS\\Results\\flooding.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones, basin, flood_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\" = 'IN'")

